03/31/25
working pi5-90

git clone https://github.com/develone/PipelineC.git -b test-dev

cd PipelineC/examples/pico-ice/

rm -rf ice_makefile_pipelinec/

devel@pi5-90:~/PipelineC/examples/pico-ice $ cp -r  ~/master-repos/pico-ice/PipelineC/pmod-ethernet-jpeg-8x8/examples/pico/ice_makefile_pipelinec/

cd ice_makefile_pipelinec/

devel@pi5-90:~/PipelineC/examples/pico-ice/ice_makefile_pipelinec $ ./build.sh
rm -f lextab.py
rm -f yacctab.py
rm -f pll_clk_mhz.h
rm -f -r pipelinec_output
rm -f pipelinec.log
rm -f pll.v
rm -f *.json *.asc *.bin *.uf2
rm -f yosys_stderr.log
rm -f dfu_util.log
echo "#define PLL_CLK_MHZ 25.0\n" > pll_clk_mhz.h
/home/devel/PipelineC/src/pipelinec ethernet_top.c --top pipelinec_top --out_dir pipelinec_output --comb --no_synth > pipelinec.log
/home/devel/oss-cad-suite//bin/icepll -q -i 12 -o 25.0 -p -m -f pll.v
/home/devel/oss-cad-suite//bin/yosys -l simple.log -q -m ghdl -p "ghdl --std=08 -frelaxed `cat pipelinec_output/vhdl_files.txt` -e pipelinec_top; read_verilog -sv ethernet_top.sv pll.v; synth_ice40 -top ethernet_top -json gateware.json" 2> yosys_stderr.log
/home/devel/oss-cad-suite//bin/nextpnr-ice40 -l nextpnr.log -q --randomize-seed --up5k --package sg48 --pcf ice40.pcf --json gateware.json --asc gateware.asc --pre-pack eth_clocks.py
/home/devel/oss-cad-suite//bin/icepack gateware.asc gateware.bin

devel@pi5-90:~/PipelineC/examples $ rm -rf net

cp -r  ~/master-repos/pico-ice/PipelineC/pmod-ethernet-jpeg-8x8/examples/net .

cd net

03/27/25 & 03/28/25 This merge of two repos PipelineC and pico-ice

mkdir PipelineC_pmod-ethernet-jpeg

cd PipelineC_pmod-ethernet-jpeg/

git clone https://github.com/develone/PipelineC.git -b test-dev

cd PipelineC/

pwd
/home/devel/PipelineC_pmod-ethernet-jpeg/PipelineC

set in .bashrc

export PIPELINEC_REPO="$HOME/PipelineC_pmod-ethernet-jpeg/PipelineC"

/hone/devel/PipelineC_pmod-ethernet-jpeg/PipelineC/example

rsync -avl /home/devel/master-repos/pico-ice/PipelineC/pmod-ethernet-jpeg-8x8/examples/pico .

This still needs to pull chgs to example/net

devel@pi5-70:~/PipelineC_pmod-ethernet-jpeg/PipelineC/examples/net $ rm -rf work.h

sudo reboot

devel@pi5-70:~ $ cd PipelineC_pmod-ethernet-jpeg/PipelineC/examples/pico/ice_makefile_pipelinec

devel@pi5-70:~/PipelineC_pmod-ethernet-jpeg/PipelineC/examples/pico/ice_makefile_pipelinec $ echo $PIPELINEC_REPO
/home/devel/PipelineC_pmod-ethernet-jpeg/PipelineC

devel@pi5-70:~/PipelineC_pmod-ethernet-jpeg/PipelineC/examples/pico/ice_makefile_pipelinec $ ./build.sh
rm -f lextab.py
rm -f yacctab.py
rm -f pll_clk_mhz.h
rm -f -r pipelinec_output
rm -f pipelinec.log
rm -f pll.v
rm -f *.json *.asc *.bin *.uf2
rm -f yosys_stderr.log
rm -f dfu_util.log
echo "#define PLL_CLK_MHZ 25.0\n" > pll_clk_mhz.h
/home/devel/PipelineC_pmod-ethernet-jpeg/PipelineC/src/pipelinec ethernet_top.c --top pipelinec_top --out_dir pipelinec_output --comb --no_synth > pipelinec.log
/home/devel/PipelineC_pmod-ethernet-jpeg/PipelineC/examples/pico/ice_makefile_pipelinec/ethernet_top.c:69:10: fatal error: examples/net/work.h: No such file or directory
   69 | #include "examples/net/work.h"
      |          ^~~~~~~~~~~~~~~~~~~~~
compilation terminated.
/home/devel/PipelineC_pmod-ethernet-jpeg/PipelineC/examples/pico/ice_makefile_pipelinec/ethernet_top.c:69:10: fatal error: examples/net/work.h: No such file or directory
   69 | #include "examples/net/work.h"
      |          ^~~~~~~~~~~~~~~~~~~~~
compilation terminated.
/home/devel/PipelineC_pmod-ethernet-jpeg/PipelineC/examples/pico/ice_makefile_pipelinec/ethernet_top.c:69:10: fatal error: examples/net/work.h: No such file or directory
   69 | #include "examples/net/work.h"
      |          ^~~~~~~~~~~~~~~~~~~~~
compilation terminated.
/home/devel/PipelineC_pmod-ethernet-jpeg/PipelineC/examples/pico/ice_makefile_pipelinec/ethernet_top.c:69:10: fatal error: examples/net/work.h: No such file or directory
   69 | #include "examples/net/work.h"
      |          ^~~~~~~~~~~~~~~~~~~~~
compilation terminated.
/home/devel/oss-cad-suite//bin/icepll -q -i 12 -o 25.0 -p -m -f pll.v
/home/devel/oss-cad-suite//bin/yosys -l simple.log -q -m ghdl -p "ghdl --std=08 -frelaxed `cat pipelinec_output/vhdl_files.txt` -e pipelinec_top; read_verilog -sv ethernet_top.sv pll.v; synth_ice40 -top ethernet_top -json gateware.json" 2> yosys_stderr.log
make: *** [Makefile:39: gateware.bin] Error 1
gateware.bin: No such file or directory

devel@pi5-70:~/PipelineC_pmod-ethernet-jpeg/PipelineC/examples/pico/ice_makefile_pipelinec $ cp ~/master-repos/pico-ice/PipelineC/pmod-ethernet-jpeg-8x8/examples/net/work.h ../../../examples/net/

devel@pi5-70:~/PipelineC_pmod-ethernet-jpeg/PipelineC/examples/pico/ice_makefile_pipelinec $ cp ../../../examples/net/work.h.orig ../../../examples/net/work.h
devel@pi5-70:~/PipelineC_pmod-ethernet-jpeg/PipelineC/examples/pico/ice_makefile_pipelinec $ ./build.sh
rm -f lextab.py
rm -f yacctab.py
rm -f pll_clk_mhz.h
rm -f -r pipelinec_output
rm -f pipelinec.log
rm -f pll.v
rm -f *.json *.asc *.bin *.uf2
rm -f yosys_stderr.log
rm -f dfu_util.log
echo "#define PLL_CLK_MHZ 25.0\n" > pll_clk_mhz.h
/home/devel/PipelineC_pmod-ethernet-jpeg/PipelineC/src/pipelinec ethernet_top.c --top pipelinec_top --out_dir pipelinec_output --comb --no_synth > pipelinec.log
/home/devel/oss-cad-suite//bin/icepll -q -i 12 -o 25.0 -p -m -f pll.v
/home/devel/oss-cad-suite//bin/yosys -l simple.log -q -m ghdl -p "ghdl --std=08 -frelaxed `cat pipelinec_output/vhdl_files.txt` -e pipelinec_top; read_verilog -sv ethernet_top.sv pll.v; synth_ice40 -top ethernet_top -json gateware.json" 2> yosys_stderr.log
/home/devel/oss-cad-suite//bin/nextpnr-ice40 -l nextpnr.log -q --randomize-seed --up5k --package sg48 --pcf ice40.pcf --json gateware.json --asc gateware.asc --pre-pack eth_clocks.py
/home/devel/oss-cad-suite//bin/icepack gateware.asc gateware.bin
devel@pi5-70:~/PipelineC_pmod-ethernet-jpeg/PipelineC/examples/pico/ice_makefile_pipelinec $ scp gateware.uf2 pi5-90:/media/devel/pico-ice/
gateware.uf2                                  100%  204KB  10.3MB/s   00:00